config/routes.rb
Rails.application.routes.draw do
  resources :fizzbuzzs do
    get 'value', on: :member
  end

  root 'fizzbuzzs#index'

end

app/models/fizzbuzz.rb
class Fizzbuzz < ActiveRecord::Base

  validates_uniqueness_of :number

  def value
    computed_value = ''
    computed_value += 'Fizz' if number % 3 == 0
    computed_value += 'Buzz' if number % 5 == 0
    computed_value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fizzbuzzs_controller.rb
class FizzbuzzsController < ApplicationController
  before_action :set_fizzbuzz, only: [:show, :edit, :update, :destroy]

  # GET /fizzbuzzs
  # GET /fizzbuzzs.json
  def index
    @fizzbuzzs = Fizzbuzz.all
  end

  # GET /fizzbuzzs/1
  # GET /fizzbuzzs/1.json
  def show
  end

  # GET /fizzbuzzs/new
  def new
    @fizzbuzz = Fizzbuzz.new
  end

  # GET /fizzbuzzs/1/edit
  def edit
  end

  # POST /fizzbuzzs
  # POST /fizzbuzzs.json
  def create
    @fizzbuzz = Fizzbuzz.new(fizzbuzz_params)

    respond_to do |format|
      if @fizzbuzz.save
        format.html { redirect_to @fizzbuzz, notice: 'Fizzbuzz was successfully created.' }
        format.json { render :show, status: :created, location: @fizzbuzz }
      else
        format.html { render :new }
        format.json { render json: @fizzbuzz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fizzbuzzs/1
  # PATCH/PUT /fizzbuzzs/1.json
  def update
    respond_to do |format|
      if @fizzbuzz.update(fizzbuzz_params)
        format.html { redirect_to @fizzbuzz, notice: 'Fizzbuzz was successfully updated.' }
        format.json { render :show, status: :ok, location: @fizzbuzz }
      else
        format.html { render :edit }
        format.json { render json: @fizzbuzz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fizzbuzzs/1
  # DELETE /fizzbuzzs/1.json
  def destroy
    @fizzbuzz.destroy
    respond_to do |format|
      format.html { redirect_to fizzbuzzs_url, notice: 'Fizzbuzz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def value
    fizzbuzz = Fizzbuzz.find(params[:id])
    respond_to do |format|
      format.json { render json: { number: fizzbuzz.number, value: fizzbuzz.value } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fizzbuzz
      @fizzbuzz = Fizzbuzz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fizzbuzz_params
      params.require(:fizzbuzz).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fizzbuzzs_helper.rb
module FizzbuzzsHelper
end

app/views/fizzbuzzs/_form.html.erb
<%= form_for(@fizzbuzz) do |f| %>
  <% if @fizzbuzz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fizzbuzz.errors.count, "error") %> prohibited this fizzbuzz from being saved:</h2>

      <ul>
      <% @fizzbuzz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fizzbuzzs/edit.html.erb
<h1>Editing Fizzbuzz</h1>

<%= render 'form' %>

<%= link_to 'Show', @fizzbuzz %> |
<%= link_to 'Back', fizzbuzzs_path %>

app/views/fizzbuzzs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fizzbuzzs</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Value</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @fizzbuzzs.each do |fizzbuzz| %>
      <tr>
        <td><%= fizzbuzz.number %></td>
        <td id="fizzbuzz-<%=fizzbuzz.number%>-value"><%= %></td>
        <td><%= link_to 'Show', fizzbuzz %></td>
        <td><%= link_to 'Edit', edit_fizzbuzz_path(fizzbuzz) %></td>
        <td><%= link_to 'Destroy', fizzbuzz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fizzbuzz', new_fizzbuzz_path %>

app/views/fizzbuzzs/new.html.erb
<h1>New Fizzbuzz</h1>

<%= render 'form' %>

<%= link_to 'Back', fizzbuzzs_path %>

app/views/fizzbuzzs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fizzbuzz_path(@fizzbuzz) %> |
<%= link_to 'Back', fizzbuzzs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FizzBuzz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>